name: money_manager
description: "A new Flutter project for managing finances."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/home_light.png
    - assets/icons/minus_light.png
    - assets/icons/plus_light.png
    - assets/icons/settings_light.png